### PR TITLE
[WIP] add webdav storage provider

### PR DESCRIPTION
**Pull request by karakayasemi**
I saw this article https://help.nextcloud.com/t/connect-your-web-app-to-nextcloud-with-webdav-fs/14563 and by using webdav-fs-client implemented oc/nc as file upload store. Since it is using webdav client, the store compatible with all WebDAV servers (NextCloud, ownCloud and so on). Currently, There are two issues that I trying to solve; 

-NextCloud/Owncloud server does not work when file locking enabled.
-I get a random following error for 50% of  the uploads : 

````
I20180522-22:44:41.959(3)? Exception while invoking method 'ufsComplete' Error: Invalid response: 404 Not Found
I20180522-22:44:41.959(3)?     at handleResponseCode (/var/www/html/Rocket.Chat/node_modules/webdav/dist/response.js:7:15)
I20180522-22:44:41.959(3)?     at /home/ssk/.meteor/packages/promise/.0.10.2.cv5il4.vcmo5++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40

### CODE REVIEW

**Comment by schiessle** [comment]
Can you enable debugging on the Nextcloud server and check the nextcloud.log. Maybe we will find more information there.

**Comment by karakayasemi** [comment]
Locking problem is gone, there is no error log in nextcloud.log. But still something wrong in request order to webdav server. Rocket.Chat is sending GET request before put request. According to logs, the file is successfully written(HTTP 201) but then deleted(HTTP 204). 
````
192.168.157.143 - admin [26/May/2018:23:04:27 +0300] "GET /server/remote.php/dav/files/admin/Rocket/tXCrsMA3t9WRsQJ64 HTTP/1.1" 404 1436 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
192.168.157.143 - admin [26/May/2018:23:04:27 +0300] "PUT /server/remote.php/dav/files/admin/Rocket/tXCrsMA3t9WRsQJ64 HTTP/1.1" 201 1295 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
192.168.157.143 - admin [26/May/2018:23:04:27 +0300] "DELETE /server/remote.php/dav/files/admin/Rocket/tXCrsMA3t9WRsQJ64 HTTP/1.1" 204 1167 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
````
Still could not resolve this problem. Investigating the other ufs-stores, no clue yet.

**Comment by karakayasemi** [comment]
I have some diagnoses about the situation which I want to share with you but still could not find any proper solution. 
The problem is on this finish listener: https://github.com/jalik/jalik-ufs/blob/a5e072011e0d32871e916e8127600f99976ccc20/ufs-store.js#L250 . 
The callback should work on the finishing of the upload but, it is somehow running before writeStream not conclude. Because of that, Rocket is sending get request before put and getting 404 error.

As far as I understand, Our Amazon S3 implementation had experienced the same problem and it solved this problem by removing this finish event and emitting their own real_finish event at the end of the upload:
https://github.com/RocketChat/Rocket.Chat/blob/e2b99ea2f38bf0a47724714c836c4ba0973a8ce2/packages/rocketchat-file-upload/ufs/AmazonS3/server.js#L128 . I tried a similar solution to AmazonS3 implementation but could not succeed.

One more thing, when I debug an upload request, If I put a breakpoint to getReadStream of the WebDAV store and wait a small amount of time, upload is succeeding.

**Comment by karakayasemi** [comment]
The pull request open in main repo. we can continue from https://github.com/RocketChat/Rocket.Chat/pull/11027

**Pull request closed without merging**
